ray-project/rayci

ray_ci/bootstrap_linux.sh
ray_ci/pipeline_ci.py
ray_ci/step.json

If `[all_tests]` is found in a commit message, run all tests

Add trigger [all_tests] to run all tests

---

ray_ci/step.json

This is needed to support testing https://github.com/ray-project/ray/pull/30011
Signed-off-by: Eric Liang <ekhliang@gmail.com>

Add SYS_PTRACE cap to build

---

ray_ci/pipeline_ci.py

Update docker version tag in ci script

---

.github/CODEOWNERS

Swap Ray CI owners to Lonnie and Cuong.

---

ray_ci/pipeline_ci.py
ray_ci/test_pipeline_ci.py

Reverts ray-project/buildkite-ci-pipelines#23

Revert "Add grouping support for ray CI pipeline."

---

ray_ci/pipeline_ci.py
ray_ci/test_pipeline_ci.py

Failed last time, let's try again.

[ci] add groups support

---

.buildkite/pipeline.yaml

Add buildkite init

---

ray_ci/test_pipeline_ci.py
ray_ci/testdata/pipeline.yml

add a full script smoke test

---

.buildkite/pipeline.yaml
.gitignore
go.mod
go.sum
raycicmd/build_id.go
raycicmd/build_id_test.go
raycicmd/env.go
raycicmd/env_test.go

adding env var reading interface and build id util functions.

init go module and add some basic util files

---

raycicmd/util.go
raycicmd/util_test.go

for the ease to edit pipeline steps from our custom definition format to buildkite's

add some util functions and tests

---

go.mod
go.sum
raycicmd/config.go
raycicmd/config_test.go

config for how to bootstrap a pipeline, with builtin config files for existing pipelines.
so that we are do not need to save configs in pipeline steps as env variables.

add config struct and parsing

---

.buildkite/pipeline.yaml
main.go
raycicmd/bk_pipeline.go
raycicmd/main.go
raycicmd/main_test.go
raycicmd/make.go
run_rayci.sh

- add a script that can be used on buildkite pipeline to build and run rayci
- add logic to generate basic, noop buildkite pipeline
- self bootstraping on rayci's ci.

tests rayci with rayci

---

raycicmd/forge.go
raycicmd/forge_test.go

used to extract the forge image name from Dockerfile names in specific forge directories.

add a function that parse forge name from filename

---

raycicmd/make.go
raycicmd/make_test.go

a rayci yaml file is a file that ends with ".rayci.yaml" or ".rayci.yml".

func that checks if it is rayci pipeline file

---

raycicmd/converter_test.go
raycicmd/main_test.go
raycicmd/util_test.go

grouping as:
1. testing
2. std packages
3. 3rd-party packages

test file import order cleanup

---

.buildkite/forge/Dockerfile.forge
.buildkite/pipeline.yaml
.buildkite/tests.rayci.yaml
raycicmd/config.go
raycicmd/make.go
raycicmd/make_test.go

creates pipeline definitions and hooks everything together. testing end-to-end.

use rayci to test rayci

---

raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/forge.go
raycicmd/forge_test.go
raycicmd/rayci_pipeline.go

so that civ2 has higher priority than civ1.

supports priority, and sets default priority to 1 for prs

---

wanda/writer_to_reader.go
wanda/writer_to_reader_test.go

this utility struct converts a writerTo to a reader. this will be used to pipe a dynamically generated tar stream a command line process for building containers.

add writerToReader

---

ray_ci/build_base_build.sh

get prepare to replace the building steps with wanda`

cleanup cpu base building script

---

raycicmd/config.go

correct more typos in yaml field names.

---

ray_ci/build_base_build.sh

this builds with limited files as build input.

when wanda yaml presents, use wanda to build

---

raycicmd/make.go

nit fix: wrap a line that is too wide

---

wanda/counting_writer_test.go

nit fix: frontload testing in imports

---

.buildkite/tests.rayci.yaml

make it clearer that it is a list value

nit: add indents to rayci.yaml

---

raycicmd/config.go
raycicmd/config_test.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/forge.go
raycicmd/forge_test.go
raycicmd/make.go
raycicmd/make_test.go

- rename tempecr to workecr
- add a forge prefix; required for wanda
- pipe the env vars into the forge step

[rayci] refactor on config and forge step

---

wanda/spec.go
wanda/spec_test.go

wanda spec file specifies the input of a image build

[wanda] add wanda spec file format and parsing

---

raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

this allows defining a builder step within the same pipeline definition yaml file

[rayci] add wanda step support in rayci pipeline definition

---

raycicmd/config.go

[rayci] fix config field name typo (again)

---

go.mod
go.sum
wanda/resolve_image.go
wanda/resolve_image_test.go

to determine and pin the container base image input before building.

[wanda] add image source resolving

---

raycicmd/config.go

so that it can upload to cache

[rayci] treat rayci as postmerge

---

raycicmd/config.go

required for caching to work, as code on pr branch will not write back after building.

[rayci] use a common shared temp ecr

---

raycicmd/converter.go
raycicmd/converter_test.go

use `envMapCopy()` on docker env keys preparing.

[rayci] fix bug that some env keys are missing

---

raycicmd/rayci_pipeline.go

so that we can run steps conditionally.

[rayci] support `if` key in steps

---

raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

make wait slightly more powerful, 'cause why not..

[rayci] allow wait step to have if and deps

---

wanda/wanda/main.go

and reduce default epoch to daily.

fix epoch bug

---

raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go

for passing in the directory that checks out ray on the machine.

[rayci] add extra env to pass into docker

---

ecosystem_ci/step.json

Closes https://github.com/ray-project/kuberay/issues/1382

[ecosystem CI] Add automatic retry on agent loss and agent shutdown

---

raycicmd/tag_filter.go

so that we can see the error if any

[rayci] pipe out stderr of tag filter command

---

raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

Allow wanda to have tags and be filtered.
Test:
- CI

[wanda] support tags

---

raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

Allow wanda to have tags and be filtered.
Test:
- CI
---------

[wanda] support tags (#115)

---

wanda/wanda/main.go

so that PR's that are not syncing from today's master branch can also cache hit.

[wanda] set cache refresh epoch back to a week

---

raycicmd/config.go

[rayci] add trainium queue into default config

---

.buildkite/tests.rayci.yaml
raycicmd/config.go
raycicmd/converter_test.go
raycicmd/make.go
raycicmd/make_test.go
raycicmd/tag_filter.go
raycicmd/tag_filter_test.go
wanda/build_input.go

and by default skip all "disabled" tags.

[rayci] add tags skipping support

---

raycicmd/bk_pipeline.go
raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go
raycicmd/util.go
raycicmd/util_test.go

so that in other previledged, non oss modes, we can use
buildkite-agent from the system

[rayci]  add option to mount bk agent when enabled.

---

raycicmd/config.go
raycicmd/rayci_pipeline.go

update field name.. forget to update it again after rename..

[rayci] add allow in yaml field name

---

ray_ci/bootstrap_linux_cpu_gpu.sh

so that CI still runs fine when the yaml files are missing.

[legacy ci] make gpu pipelines optional

---

raycicmd/config.go

tag `skip-on-premerge` will skip on premerge pipeline.

[rayci] add tag to skip on pr/premerge pipeline

---

raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/make.go
raycicmd/make_test.go
raycicmd/rayci_pipeline.go

when a group have tags, the entire group can be skipped based on tag filtering.

[rayci] allow groups and wait step to have tags

---

raycicmd/converter.go
raycicmd/make.go
raycicmd/make_test.go
raycicmd/tag_filter.go
raycicmd/tag_filter_test.go

step with no tags should always run

[rayci] fix tags filter issue

---

raycicmd/wanda.go
raycicmd/wanda_test.go

for pipelines that do not support all builder instance types

[rayci] support builder skip queue mapping

---

.buildkite/tests.rayci.yaml
raycicmd/bk_pipeline.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go
wanda/forge_test.go

this allows setting a container registry that in the runner and allow it to be accessible by the docker daemon

[rayci] support port publishing on runner steps

---

raycicmd/bk_pipeline.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

so an entire group can depend on another buildkite step.

[rayci] allow group to have depends_on

---

raycicmd/tag_filter.go
raycicmd/tag_filter_test.go

so that we can scripts that allow people to opt-in and run everything.

[rayci] add special '*' to running all tests.

---

.buildkite/windows.rayci.yaml
.buildkite/windows_docker.sh
raycicmd/bk_pipeline.go

Mount window host dockerd so we can run docker inside docker in windows
Test:
- CI

[ci] mount window host dockerd

---

ray_ci/step_linux.json

[v1] backport civ1 gpu test fix

---

ray_ci/step_macos.json

required for rebuilding wheels from long time ago.

[v1] double intel macos timeout

---

.buildkite/hello.txt
.buildkite/windows.Dockerfile
.buildkite/windows.rayci.yaml
.buildkite/windows.wanda.yaml
raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/wanda.go
run_wanda.sh
wanda/build_input.go
wanda/docker_cmd.go
wanda/docker_cmd_test.go
wanda/forge.go
wanda/resolve_image_test.go

[rayci] winda

---

.buildkite/fix-windows-container-networking.ps1
.buildkite/windows.rayci.yaml
.buildkite/windows_docker.sh

Add a test to pull wanda image and run

[ci] add test for wanda run

---

raycicmd/bk_pipeline.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

this allows running k8s-in-docker tests.

[rayci] supports specifying docker network

---

.buildkite/macos.rayci.yaml
raycicmd/converter.go

Support macos job in rayci. For macos do not use docker plugin
Test:
- CI

[rayci] support macos job

---

ray_ci/bootstrap_linux.sh
ray_ci/bootstrap_linux_cpu_gpu.sh

also:
- skip gpu base image building if gpu yaml files do not exist
- skip ml kick off if ml yaml file does not exist
- various styling cleanup

[civ1] remove early kick off

---

ray_ci/bootstrap_linux_cpu_gpu.sh

so that we can remove the last build pipeline.

[legacy ci] make build pipelines optional

---

.buildkite/macos.rayci.yaml
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

Support block step (for blocking macos run on premerge)
Test:
- CI

[ci] support block step

---

ray_ci/bootstrap_linux.sh
ray_ci/bootstrap_linux_arm64.sh
ray_ci/bootstrap_linux_cpu_gpu.sh

only run civ1 when determine tests to run want to run rllib contrib tests

[legacy] check civ1 sunset mark for skipping

---

.buildkite/macos.rayci.yaml
raycicmd/converter.go
raycicmd/converter_test.go

Add macos sandbox plugin for civ2 (similar to civ1: https://github.com/ray-project/rayci/blob/main/ray_ci/step_macos.json#L4)
Test:
- CI

[rayci] add macos sandbox plugin

---

.buildkite/forge.Dockerfile

required after some CI pool's upgrade

fix ci, add new docker group id in forge

---

ray_ci/bootstrap_mac.sh

it is all removed on master now.

[legacy ci] add macos pipeline skipping

---

.buildkite/macos.rayci.yaml
.buildkite/windows.rayci.yaml
raycicmd/make.go
raycicmd/make_test.go
raycicmd/rayci_pipeline.go

so that we can put unimportant tests (like macos) at the bottom of the pipeline.

[rayci] add sort key to rayci groups

---

.buildkite/macos.rayci.yaml

as it often blocked by a long queue

make intel silicon macos test optional

---

raycicmd/bk_pipeline.go

Add retries for more exit codes. This one in particular: https://buildkite.com/ray-project/postmerge/builds/2611#018d326f-b084-40ca-a672-1cfaf57b9cb7

[ci] add retries for more exit code

---

raycicmd/bk_pipeline.go

[ci] add retries for 53 exit code

---

raycicmd/build_info.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/main.go
raycicmd/make_test.go
raycicmd/step_converter.go
raycicmd/util.go
raycicmd/util_test.go
raycicmd/wanda.go

add stepConverter interface, and implement wanda/block/wait step converters. make the converter file more modularized and easier to read.
pure refactoring. nothing changed.

[rayci] abstract out step conversion

---

.buildkite/release.rayci.yaml
raycicmd/config.go

Add release pool for ray-branch
Test:
- CI

[ci] add release pool for ray-branch

---

.buildkite/release.rayci.yaml

otherwise it might run into image not found.

[ci] add forge dependency for release queue test

---

raycicmd/make.go
raycicmd/rayci_pipeline.go
raycicmd/rayci_pipeline_test.go

[rayci] create a lessThan function for pipeline group

---

raycicmd/dep_graph.go
raycicmd/dep_graph_test.go

for auto including depended test jobs

[rayci] add utilities that expands dependencies

---

raycicmd/command_step.go
raycicmd/converter.go

increases locality, removes circular dependency on files
also uses switch for special job env switching

[rayci] move command step constants into command_step

---

raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/make.go
raycicmd/step_filter.go
raycicmd/step_filter_test.go

making the filtering more generic, not only to tags.

[rayci] rename tagsFilter into stepFilter

---

raycicmd/converter.go
raycicmd/step_node.go

so that it is clearer that, well, they are sub-steps.

[rayci] rename steps in stepNode to subSteps

---

raycicmd/make.go
raycicmd/make_test.go

broken by past refactoring. also adds tests.

[rayci] fix multi dir scanning

---

raycicmd/converter.go
raycicmd/make.go
raycicmd/step_filter.go
raycicmd/step_filter_test.go
raycicmd/step_node.go
raycicmd/step_node_test.go

so that callers do not access tags field directly

[rayci] move tags checking logic into stepNode

---

raycicmd/step_filter_test.go

add more tests for `accept()` call

[rayci] add more tests to accept function

---

raycicmd/converter.go
raycicmd/step_node.go
raycicmd/step_node_set.go
raycicmd/step_node_set_test.go

A container that can save a set of nodes, and provides querying
nodes based by ID, and querying by key after building the key index.

[rayci] add step node set

---

raycicmd/step_node.go
raycicmd/step_node_set.go
raycicmd/step_node_set_test.go

for tracking which nodes to include or reject.

[rayci] add dependency tracking in stepNodeSet

---

raycicmd/converter.go
raycicmd/converter_test.go

- when a node is rejected/disabled, also disables all its dependency nodes
- when a ndoe is included/selected, also includes all its depended nodes

[rayci] add smarter dependency tracking 

---

.buildkite/forge.Dockerfile
run_rayci.sh
run_wanda.sh

upgrade golang compiler version

---

raycicmd/rayci_pipeline.go
raycicmd/step_converter_test.go

- Add if as key for trigger step
- Unit tests
- Using this branch on this pipeline build works: https://buildkite.com/ray-project/release-automation/builds/165#018ded20-2e45-4557-ba0a-cc5b27864045

[raycicmd] Add if key for trigger step

---

raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

- Add `allow_dependecy_failure` as a key for command step

[rayci] Add allow_dependecy_failure key for command step

---

raycicmd/rayci_pipeline.go

Add `key` attribute in both `wait` and `block` step

[rayci] Add key in wait step and block step

---

raycicmd/config.go

doc / comment line too long; has 84 chars.

[rayci] nit: limit lines to 80 chars

---

raycicmd/bk_pipeline.go
raycicmd/converter_test.go

docker plugin seems to accept both.. but let's use the recommended / documented one.

[rayci] use the idomatic key for agent mount

---

go.mod
run_rayci.sh
run_wanda.sh

[rayci] update go language compiler version

---

raycicmd/step_node.go
raycicmd/step_node_test.go

returns true when the node hits the selection set.

[rayci] add node a member function for step selection

---

raycicmd/main.go
raycicmd/main_test.go

just to increase test coverage

[rayci] add unit test for execWithInput

---

raycicmd/step_filter.go
raycicmd/step_filter_test.go

allows people and robots to manually select nodes to run

[rayci] add id/key selection filter

---

raycicmd/converter.go
raycicmd/make.go
raycicmd/make_test.go

so that we can now select one or a subset of test jobs to run.

[rayci] connect and enable the selector

---

raycicmd/config.go
raycicmd/config_test.go

As title, store this in rayci to obscure its definition.

[rayci] microcheck pipeline rayci config

---

.buildkite/forge.Dockerfile
go.mod
raycicmd/bk_pipeline.go
raycicmd/config.go
run_rayci.sh

and also fix line width wider than 80 chars

[go] upgrade compiler to 1.22.3

---

LICENSE

add apache 2 license

---

.buildkite/forge.Dockerfile
go.mod
run_rayci.sh
run_wanda.sh

[go] upgrade go compiler

---

reefd/reefd/main.go
reefd/serve.go
reefd/serve_test.go

[reefd] add http server skeleton

---

ecosystem_ci/step.json

[kuberay] add artifact paths to kuberay ci

---

raycicmd/command_step.go
raycicmd/config.go
raycicmd/converter_test.go
raycicmd/main.go
raycicmd/make.go

[rayci] limit source code to 80-chars max line width

---

raycicmd/command_step.go
raycicmd/converter_test.go

make it easier to select with `RAYCI_SELECT`

[rayci] print out rayci step ids in command steps

---

raycicmd/converter_test.go
raycicmd/step_filter.go
raycicmd/step_filter_test.go
raycicmd/step_node.go
raycicmd/util.go
raycicmd/util_test.go

so that one can also select a set of tags to run.

[rayci] add support for tag selecting

---

reefd/reaper.go
reefd/reaper_test.go

lines too wide & inconsistent use of receiver names

[reefd] address some formatting and linting issues

---

raycicmd/bk_pipeline.go
raycicmd/command_step.go
raycicmd/config.go

required for adopting rayci into more repos.

[rayci] allow setting different docker plugin config

---

.buildkite/macos.rayci.yaml

the test does not run much, but often needs to wait for a long time

[ci] add block for apple silicon test

---

raycicmd/bk_pipeline.go
raycicmd/command_step.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

so that we can use rayci to run a job that assumes into another role

[rayci] add aws assume role support

---

raycicmd/main.go
raycicmd/main_test.go

this allows reusing most of the configs but with a different set of pipeline definition files

[rayci] allow specifying buildkite dirs from flags

---

raycicmd/rayci_pipeline.go
raycicmd/step_converter_test.go

for more details of the field, see:
https://buildkite.com/docs/pipelines/configure/step-types/block-step#block-step-attributes

[rayci] support more fields in block state

---

raycicmd/command_step.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

allowing steps to specify a shorter timeout

[rayci] add explicit time out support

---

raycicmd/command_step.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

so that it will not be redeclared

[rayci] support specifying a default job env for a group

---

wanda/list_src.go
wanda/list_src_test.go

preparing for listing files with wanda src fields

[wanda] add utility functions for listing files
