ray-project/rayci

ray_ci/bootstrap_linux.sh

Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>
If we make changes to compiled Python code, we shouldn't early kick off, as they will not be reflected in CI.
Env var set by https://github.com/ray-project/ray/pull/29870

No early kickoff for compiled Python files

---

ray_ci/bootstrap_linux.sh
ray_ci/bootstrap_linux_arm64.sh
ray_ci/bootstrap_linux_cpu_gpu.sh
ray_ci/build_base_arm64.sh
ray_ci/step.json

This splits the bootstrap_linux script into two, one for CPU/GPU and one for ARM64 pipelines.
ARM64 builds have to run on ARM64 machines, so we need separate images and a separate pipeline.

Arm64 base image build and pipeline kick-off

---

ray_ci/bootstrap_linux.sh
ray_ci/bootstrap_linux_cpu_gpu.sh
ray_ci/pipeline_ci.py
ray_ci/step.json
ray_ci/test_pipeline_ci.py

This PR fixes [broken early kickoff tests](https://github.com/ray-project/ray/issues/31476) in two ways:
1. We checkout some original files from the master branch (i.e. the base early kick off image) before running the test. This should restore compatibility with the compiled raylet in most cases (some major API changes will not be found)
2. Add a `[no_early_kickoff]` flag that disables early kick off
Closes https://github.com/ray-project/ray/issues/31476

Fix early kick off: Add flag to disable and checkout raylet codes

---

ecosystem_ci/build_pipeline.py
ecosystem_ci/step.json

KubeRay needs Docker in Docker to run their test suites.
This PR updates the ecosystem pipelines to start a dind daemon and connect to it.
Here is an example on how to use it: https://github.com/krfricke/ray-ecosystem-dev/commit/511782b9e7df15dd7ca4b59152826dfd10f56678
The pipeline needs to run on an image that either has docker installed or can install docker later.
Any docker _builds_ must happen in the `/shared` directory, which is shared between the host VM and the docker container running on CI.
For example, here we just start a ubuntu container and call a `install_docker.sh` script that installs docker. The `build.sh` image will then later build a docker image.
```
- label: Second pipeline
commands:
- echo Second command
- bash install_docker.sh
- docker ps
- bash build.sh …
```

Add Docker-in-Docker support for Ecosystem pipelines

---

ray_ci/step_linux.json

This PR added `apparmor=unconfined` to container so that it can mount the root. With this we should isolate the tests and put each test into a sandbox.

Add `apparmor=unconfined` to container

---

ray_ci/step_linux.json

This is required to build all docker images when horrible cache misses.

Increase build timeout on CI to 5 hours.

---

ray_ci/bootstrap_linux.sh
ray_ci/bootstrap_linux_cpu_gpu.sh

Early kickoff currently suffers more often from mismatch between core files and library files. Until this is resolved, we should disable automatic early kick off and only enable on opt-in.
Closes #19, closes #20

Require opt-in for early kickoff

---

external_code_tracker/glue.js
external_code_tracker/test_track_code.js
external_code_tracker/track_code.js

As discussed in https://github.com/ray-project/ray/pull/35261, we should keep the logic to check for changed files in a separate, testable repository.

Scripts for tracking external code changes

---

ray_ci/pipeline_ci.py
ray_ci/test_pipeline_ci.py

So that we can support grouping.
One can add a `#ci:group=MY_GROUP_NAME` to put all the steps into a group with name `MY_GROUP_NAME`.

Add grouping support for ray CI pipeline.

---

ray_ci/bootstrap_linux_cpu_gpu.sh

`pipeline.build.yml` in ray is quite long, breaking it can make it possible to show as different groups.

make it possible to break pipeline.build.yml into multiple files.

---

ray_ci/pipeline_ci.py

The current map command function assumes that a step always has some "command" as a key. This is not entire true, in particular for trigger step like in https://github.com/ray-project/ray/pull/36972/files.
Do not update the step if a key is not part of the step.
Check error in https://buildkite.com/ray-project/oss-ci-build-pr/builds/27258#01890995-47ad-4632-9ca1-508796477dba
```
Traceback (most recent call last):
--
  | File "/tmp/tmp.FL5QpzPzXg/ray_ci/pipeline_ci.py", line 317, in <module>
  | main()
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
  | return self.main(*args, **kwargs)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
  | rv = self.invoke(ctx)
  | File …
```

[ci] fix map command

---

ray_ci/pipeline_ci.py

https://github.com/ray-project/ray/pull/36972 adds triggering steps as part of pipeline.yaml file. The current pipeline_ci.py assumes that all steps are command steps though.
Separate command steps and non-command steps, and just leave the format of non-command steps as they are.

[ci] Support triggering of non-command steps

---

ray_ci/pipeline_ci.py

69cb01c61f97469941a0609e54f0f6fbdd3dea21 add supports for non-command steps in ray-ci. However, we intentionally support only command steps, so undo it.

[ci] revert 69cb01c61f97469941a0609e54f0f6fbdd3dea21

---

.buildkite/pipeline.yaml

to prevent regression on python scripts.
runs in amazonlinux:2 because that is what is used in buildkite ami.

add ray_ci python test

---

raycicmd/config.go

new blocking pipeline
not used anywhere though, because a pipeline is treated as a PR pipeline by default.

add v2 pipeline id

---

raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go

also removes dockerless mode, was only used for testing in the early days.

add pipeline wise env var support

---

raycicmd/config.go

auto saves cost. use of large instances has to specify explicitly.

change default queue to small rather than large

---

wanda/counting_writer.go
wanda/counting_writer_test.go

this is required for wrapping a tarball stream, which will be used for providing deterministic context input for a docker image build.
wanda is the name of the new command line tool for building images with fast caches.

add a counting writer

---

raycicmd/config.go

fix yaml key typo after field renaming.

---

ray_ci/build_base_build.sh

make the input for base image picking irrelevant to the build commit on local build. this will make the build args part of the input deterministic and cachable.
the `BUILDKITE_PULL_REQUEST` and `BUILDKITE_COMMIT` will also be removed from follow up changes.

make tags in base image building deterministic

---

wanda/tar_meta.go
wanda/tar_meta_test.go

used to capturing file mode of build input files, but unifying all user id and group id to root, so that the result is deterministic.

[wanda] 1/ add tar meta and tests

---

wanda/digest.go
wanda/digest_test.go

generates digests with `"sha256:"` prefix.

[wanda] 0/ add digest utility to capture digest strings

---

raycicmd/config.go

which runs on branch runners and can write into bazel cache and call lambda.
after this is merged and deployed we will disable lambda calling from premerge.

[rayci] add postmerge pipeline support

---

raycicmd/config.go

we will stop using "if it is a PR" for checking.
Rather, simply use if it runs on the premerge pipeline or the postmerge pipeline. this will enable people to manually run and also for insiders to run on non-master but still has the power to write to caching infra and/or perform releases.

config: add a cache readonly mark for PR configs

---

raycicmd/converter.go
raycicmd/converter_test.go

rather than putting them inside docker's env list.
this makes it a common setup that can be used also in builder steps, which do not run inside dockers.

move env out to buildkite env list

---

raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/main.go
raycicmd/make.go
raycicmd/make_test.go

so that `run_wanda.sh` can load and compile from the same branch.
useful for debugging, and required for e2e testing on rayci's own pipeline.

[raycicmd] pipe through RAYCI_BRANCH env var

---

ray_ci/build_base_build.sh

new rayci wanda steps only populates `BUILDKITE_BAZEL_CACHE_URL`, but not `REMOTE_CACHE_URL`

[legacy bootstrap] unify to BUILDKITE_BAZEL_CACHE_URL

---

.gitignore
release.sh

for releasing rayci and wanda binaries.
after we have more stable releases, we can just download bins rather than build from source all the time.

add a simple release script to build release bins

---

run_wanda.sh

though we can still interpret `install rayci` to be `download and install the rayci repo`, which is also ok..

say install wanda rather than install rayci

---

raycicmd/bk_pipeline.go

Mount buildkite artifact folder to the docker that runs CI, so build jobs can stores wheel and jar into buildkite artifacts
Test:
- CI

[ci] Mount buildkite artifact folder to docker

---

.buildkite/pipeline.yaml

[ci] use small runner for launching and legacy

---

wanda/forge.go

so that we can use prefix for more aggressive ecr tag garbage collection for non-cache, temp tags.

[wanda] change cache prefix to `z-`

---

raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/make.go
raycicmd/make_test.go
raycicmd/rayci_pipeline.go
raycicmd/tag_filter.go
raycicmd/tag_filter_test.go
raycicmd/util.go
raycicmd/util_test.go

Allow rayci to run an arbitrary shell script that outputs a list of tags. This list of tags will be used to filter steps that are tagged with certain tags.
Test:
- CI
- skip core/serverless https://buildkite.com/ray-project/dev/builds/74
- run everything: https://buildkite.com/ray-project/dev/builds/75

[rayci][coverage] filter steps by tag

---

wanda/forge.go
wanda/spec.go
wanda/spec_test.go

this allows using wanda spec file as a template, and enables to use it in a buildkite command step that has matrix.

[wanda] add env var expansion in wanda spec file

---

raycicmd/config.go
raycicmd/converter.go
raycicmd/converter_test.go

when an agent queue is mapped to `~`, will skip the runner job.

[rayci] add runner job skipping based on queue / instance type

---

raycicmd/config.go
raycicmd/config_test.go
raycicmd/converter.go
raycicmd/rayci_pipeline.go
raycicmd/wanda.go

Allow wanda to pick different builder types. This is required to run tests on aarch64.
Test:
- CI

[ci] allow wanda to specify instance type

---

.buildkite/forge.rayci.yaml
raycicmd/bk_pipeline.go

Enable automatic retries for general errors (wheel, docker, java, etc.). We changed test failure exit code to 42 in https://github.com/ray-project/ray/pull/41174 so this won't hide flaky tests.
Test:
- CI

[ci] automatic retries for general errors

---

ray_ci/bootstrap_linux_cpu_gpu.sh

pipeline.test.yaml will be deleted in https://github.com/ray-project/ray/pull/41598. The only thing that this pipeline right now is the LinkCheck, which is also fixed and moved to civ2 in the mentioned PR. 
Test:
- CI

[ci] bye pipeline.test.yaml

---

.buildkite/windows_docker.sh

Use curl instead of wget to download docker binary
Test:
- CI

[ci] fix windows docker

---

raycicmd/bk_pipeline.go

The exist code for dead windows spot instance is 3221225786 (https://buildkite.com/ray-project/postmerge/builds/2161#018c6968-6ee9-44c8-9cd2-3b41422f73b2) (as opposed to -1 or 255 in linux). Add it to the list for auto-retries.
Test:
- CI

[ci] retry windows spot instances

---

.buildkite/hooks/pre-command
.buildkite/windows.rayci.yaml
raycicmd/bk_pipeline.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

Add artifact dir for windows. Create a new windows jobenv that mounts artifact dir, this is for safe roll out of this feature (the new jobenv requires the existent of the artifact dir that needs to set up in pre-commit).
Test:
- CI

[rayci] add artifact dir for windows

---

ray_ci/build_base_build.sh

Fix base images. The wanda name changed in ray repository.
Test: https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/551

[ci] fix base images

---

ray_ci/build_base_build.sh

Forgot to update the ml base. Previous PR run test the wrong way too so didn't catch this.
Test: https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/553 (set PIPELINE_REPO_BRANCH="can-fix-base-02")

[ci] fix base again

---

wanda/docker_cmd_test.go
wanda/forge_test.go

and skipping the test that runs only on Linux
also runs the `TestForgeWithWorkRepo` test on buildkite.

[rayci] allow running unit tests on osx

---

ecosystem_ci/step.json

Not sure if it is possible to trigger KubeRay CI against this PR before merging, but if it's possible, that would be ideal.
This PR updates the version of the dind plugin in order to get the changes from https://github.com/ray-project/dind-buildkite-plugin/pull/1 which pins the `dind` version to fix KubeRay CI.
Reference for the pinning syntax: https://buildkite.com/docs/plugins/using#pinning-plugin-versions
Closes https://github.com/ray-project/kuberay/issues/1859

Pin dind version for KubeRay CI

---

raycicmd/util_test.go

the function under test has name of `toStringList`

change test name from TestToStringList

---

raycicmd/bk_pipeline.go

Windows CI jobs might swallow errors when the errors happen in the middle of the command list. This PR runs bash with both -e and -o pipefail options to fix that.
Test:
- CI, check that it fails here https://buildkite.com/ray-project/rayci/builds/736#018d53fc-ec69-4555-898b-6d45ca121f5f

[ci] fix window shell error

---

raycicmd/make_test.go

otherwise it can generate invalid pipelines

[rayci] use unique keys in rayci

---

raycicmd/step_converter.go
raycicmd/step_converter_test.go

block/wait steps need to be treated in special ways in dependency tracking, so add a utility function for it.
also adds more unit tests for basic step converter for block and wait steps.

[rayci] add block/wait step check

---

raycicmd/step_node.go
raycicmd/step_node_test.go

can add dependencies and reverse dependencies, and maintain as a set.
the dependencies are for including: when a step is included, its dependencies also need to be included.
and the reverse dependencies are for rejecting: when a step is rejected/disabled, its reverse dependencies (dependents) also need to be rejected.

[rayci] add dependency tracking ability in stepNode

---

raycicmd/bk_pipeline.go

Add automated retries for buildkite jobs that return 126 as exist code. This captures transient windows build error. Example: https://buildkite.com/ray-project/postmerge/builds/2850#018d7afa-09fd-40ad-ad28-7fb4b394026c
Test:
- CI

[ci] Retry transient windows build error

---

raycicmd/bk_pipeline.go
raycicmd/bk_pipeline_test.go
raycicmd/make.go

some small refactoring to make `make.go` a bit easier to read.

[rayci] add a total steps method for bk pipelines

---

raycicmd/command_step.go
raycicmd/config.go
raycicmd/converter_test.go

so that we can adjust behavior of the CI pipeline on scheduled builds.

[rayci] adding RAYCI_SCHEDULE env var to pass through postmerge ci jobs

---

raycicmd/rayci_pipeline.go
raycicmd/step_converter_test.go

Apparently Buildkite does support `key` attribute for every step even though they are not listed in the documentation: https://forum.buildkite.community/t/step-key-for-trigger-steps/1208
Adding `key` here so we can use it for dependency chain in release automation pipeline

[rayci] Add key in trigger step allowed key list

---

raycicmd/bk_pipeline.go

Add more automated retries for transient error code. This time it's java. Example: https://buildkite.com/ray-project/premerge/builds/21717#018e343b-c8b3-4867-bf23-adaa6bfe3eac

[ci] add retries for java tests

---

.buildkite/release.rayci.yaml
release.sh

`rayci` only supports linux amd64, `wanda` supports linux amd64, arm64 and windows amd64.

[rayci] build release binaries for all supported platforms

---

run_rayci.sh
run_wanda.sh

saves about 40s of bootstrap time on critical path, and maybe same amount of time on every builder job.

[rayci] bootstrap: download and use released binary

---

raycicmd/command_step.go
raycicmd/converter.go
raycicmd/converter_test.go
raycicmd/step_converter.go
raycicmd/step_converter_test.go
raycicmd/wanda.go

so that the jobs of the step can know what step id they are using, and it is easier for human to tell too.

[rayci] send in rayci's step id as env var

---

raycicmd/config.go
raycicmd/config_test.go

I plan to reuse the `postmerge` pipeline to create a build that can run one test target (for bisecting purpose). Add an env variable I can pass down to a step to run only a single test target.

[ci] add RAYCI_BISECT_TEST_TARGET env key to postmerge pipeline

---

raycicmd/command_step.go
raycicmd/config.go
raycicmd/converter_test.go

Disable it by setting it to 1 (instead of just removing the line), because the command definition expects the `BUILDKITE_PARALLEL_JOB_COUNT` environment to be set. This is so that we can turn this off on microcheck.
Test:
- CI

[rayci] add a flag to disable parallelism in buildkite definition

---

raycicmd/bk_pipeline.go

As we move now save cost with periodic run, microcheck and have automation to decide if a test is flaky enough to be a release blocker, i'm thinking about auto retrying test flakiness, to avoid issues when a test blocks a release when it is not flaky enough
let's discuss
Test:
- CI

[rayci] auto retries of test flakiness

---

raycicmd/bk_pipeline.go
raycicmd/build_info.go
raycicmd/config.go
raycicmd/main.go
raycicmd/main_test.go
raycicmd/make.go
raycicmd/make_test.go

Add buildkite notification upon build failures. Notification is sent to the owner of the build (buildkite syntax: https://buildkite.com/docs/pipelines/notifications).
Enable notification for microcheck for now. This will allow folks to know build issues faster.
Test:
- CI 
- I added a failure into rayci CI in a previous commit and check that I get notified

[rayci] add buildkite notification

---

raycicmd/converter_test.go
raycicmd/rayci_pipeline.go

Allow `concurrency` and `concurrency_group`; this is require to rate limit the concurrent run of certain release test types (see https://github.com/anyscale/llm-forge/pull/387)
Test:
- CI

[rayci] allow concurrency key in buildkite step

---

raycicmd/command_step.go
raycicmd/config.go
raycicmd/converter_test.go
raycicmd/util.go
raycicmd/util_test.go

- Allow to restrict the list of concurrency group; or allow everything if the restricted list is not provided
- Restrict the list of concurrency group for premerge and microcheck (empty list means that the concurrency group is not allowed)
Test:
- CI

[rayci] allow to restrict the list of concurrency group

---

raycicmd/config.go
raycicmd/converter_test.go
raycicmd/make.go
raycicmd/make_test.go
raycicmd/step_filter.go
raycicmd/step_filter_test.go

and set as false by default. when it is set to false, this will shake off unnecessary steps that have no tags when tag based conditional testing is enabled.
this is a change on the default behavior.

[rayci] add option noTagMeansAlways

---

raycicmd/step_converter.go

so that it is not always "wait" type.

[rayci] mention the right step type in error message

---

wanda/cache_epoch.go
wanda/cache_epoch_test.go

Splitting epoch week into group A & group B (and appending to the epoch) due to exceeding container registry's 1000 tag limit intermittently

Updating epoch to include 2 groups for each week

---

wanda/forge.go

so that it works properly in the case of windows systems

[wanda] add filepath.FromSlash to properly handle slashes

---

wanda/list_src.go
wanda/list_src_test.go

from a working directory.
- single file listing is still supported
- if the file spec line ends with a `/` it is treated as a directory
- if the file spec line's base name contains `*` or `?`, then it is treated as a file name glob

[wanda] add functions that can list source files

---

wanda/forge.go
wanda/forge_test.go
wanda/spec.go
wanda/testdata/hello-nocache.wanda.yaml

allows running a wanda build without caching enabled. this helps on building images which contents are fast to build but changing frequently. if these images are cached, it can spam the container registry and make the registry run out of image count quota if it is an ECR.

[wanda] add `disable_caching` option
